# Generated by Django 5.2.14 on 2026-05-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('yesterday', models.TextField(blank=True, default='')),
                ('today', models.TextField(blank=True, default='')),
                ('blockers', models.TextField(blank=True, default='')),
                ('raw_ai_response', models.TextField(blank=True, default='')),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activities', models.ManyToManyField(blank=True, to='integrations.activity')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
