# Generated by Django 5.2.14 on 2026-05-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standup',
            old_name='blockers',
            new_name='tomorrow',
        ),
        migrations.RemoveField(
            model_name='standup',
            name='yesterday',
        ),
    ]
