# Generated by Django 5.2.14 on 2026-05-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('github', 'GitHub'), ('linear', 'Linear'), ('slack', 'Slack')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('github', 'GitHub'), ('linear', 'Linear'), ('slack', 'Slack')], max_length=20)),
                ('activity_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('external_id', models.CharField(max_length=255)),
                ('repository', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_id', models.CharField(blank=True, default='', max_length=100)),
                ('channel_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('previous_status', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'ordering': ['-occurred_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id', 'activity_type'), name='unique_source_external_activity')],
            },
        ),
    ]
