# Generated by Django 5.2.14 on 2026-05-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='source',
            field=models.CharField(choices=[('local_git', 'Local Git'), ('github', 'GitHub'), ('linear', 'Linear'), ('slack', 'Slack')], max_length=20),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='integration_type',
            field=models.CharField(choices=[('local_git', 'Local Git'), ('github', 'GitHub'), ('linear', 'Linear'), ('slack', 'Slack')], max_length=20, unique=True),
        ),
    ]
