from standups.models import Standup


def format_standup(standup: Standup) -> str:
    lines = []
    lines.append(f"*Daily Standup — {standup.date}*")
    lines.append(f"_Auto-generated by lala's standup bot_")
    lines.append("")

    if standup.today:
        lines.append("*Today*")
        lines.append(to_slack_bullets(standup.today))
        lines.append("")

    if standup.tomorrow:
        # Friday → say "Monday" instead of "Tomorrow"
        next_label = "*Monday*" if standup.date.weekday() == 4 else "*Tomorrow*"
        lines.append(next_label)
        lines.append(to_slack_bullets(standup.tomorrow))
        lines.append("")

    tokens = standup.prompt_tokens + standup.completion_tokens
    if tokens:
        lines.append(f"_Tokens used: {tokens} (in: {standup.prompt_tokens}, out: {standup.completion_tokens})_")

    return "\n".join(lines)


def to_slack_bullets(text: str) -> str:
    result = []
    for line in text.splitlines():
        stripped = line.lstrip()
        if stripped.startswith("- "):
            indent = len(line) - len(stripped)
            if indent > 0:
                result.append("    \u25E6 " + stripped[2:])
            else:
                result.append("\u2022 " + stripped[2:])
        else:
            result.append(line)
    return "\n".join(result)


def format_raw_activities(activities) -> str:
    if not activities:
        return "\nNo activities found for this period.\n"

    lines = []
    lines.append("")
    lines.append("*Raw Activities*")

    current_source = None
    for activity in activities:
        if activity.source != current_source:
            current_source = activity.source
            lines.append("")
            lines.append(f"*[{current_source.upper()}]*")

        timestamp = activity.occurred_at.strftime("%Y-%m-%d %H:%M")
        lines.append(f"  _{timestamp}_ {activity.activity_type}: {activity.title}")
        if activity.url:
            lines.append(f"           {activity.url}")

    lines.append("")
    lines.append(f"_Total: {len(activities)} activities_")
    lines.append("")

    return "\n".join(lines)
